Added internship Model + CRUD
djunicode/information-portal pull request #33
Opened 2023-04-29 13:31 UTC by Smit-Dama

Internship Model + CRUD Done
Solves issue #8

2023-04-29 16:14 UTC, codingmickey requested changes

2023-04-29 16:14 UTC, codingmickey commented on backend/routes/internshipRoutes.js
> +router.post('/add', verifyjwt, addInternship);
- don't write `/add` in the route if it's a POST route and in the parent `/internship` it's often best practice and understood to be a route for *adding internships*

2023-04-29 16:14 UTC, codingmickey commented on backend/routes/internshipRoutes.js
> +router.delete('/delete/:id', verifyjwt, deleteInternship);
Same here remove `/view/` `/viewbyid/` `/update/` `/delete/`

Also for filters use query not parameters in the path

2023-04-29 16:14 UTC, codingmickey commented on backend/controllers/internship.controller.js
> +        const id = req.params.id;
as mentioned in the router.js update this to use query :)

2023-04-30 14:09 UTC, Smit-Dama commented
Internship route changes implemented

2023-05-01 09:41 UTC, Smit-Dama commented
Research Work Model + CRUD pushed
Solves issue #11

2023-05-01 17:43 UTC, codingmickey commented
From next time always make separate PRs for separate issues so that they're easy to track as well as review..

2023-05-01 19:02 UTC, codingmickey requested changes
The same changes are to be made for the research paper route

2023-05-01 19:02 UTC, codingmickey commented on backend/controllers/internship.controller.js
> +            var internships = await Internship.find({_id:id});
viewing a single internship should be another route 😉

2023-05-01 19:02 UTC, codingmickey commented on backend/controllers/internship.controller.js
> +            var internships = await Internship.find({user_id:req.user._id});
instead of making the variable `var` make a top-level `let` variable and then change value when required

2023-05-01 19:02 UTC, codingmickey commented on backend/controllers/internship.controller.js
> +            var internships = await Internship.find({user_id:req.user._id ,status:status });
add sorting as well as pagination. I know this is an overkill for a single user.. but this will be very helpful when making admin UI

Check this as a reference which I'd done for a past project
![image](https://user-images.githubusercontent.com/42518907/235510416-cfbbd612-351c-469c-9819-dd633ef72a9e.png)

you can also add a search feature later.. 😉

2023-05-01 19:02 UTC, codingmickey commented on backend/controllers/internship.controller.js
> +            var internships = await Internship.find({_id:id});
![image](https://user-images.githubusercontent.com/42518907/235511590-d1e30ec9-1d0d-4b2d-a6d6-63a19659fdcc.png)

2023-05-11 17:56 UTC, codingmickey commented
@Smit-Dama when can I expect you to complete this?

2023-06-11 06:25 UTC, codingmickey commented
Closes #8 and #11

2023-06-11 06:25 UTC, merged